apiVersion: v1
kind: Service
metadata:
  name: cloudsmart-service
  labels:
    app: cloudsmart
spec:
  selector:
    app: cloudsmart

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
